<?php declare(strict_types=1);

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function(string $class): void {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                ___CLASSLIST___
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require ___BASEDIR___$classes[$cn];
        } else {
            $dir = getcwd();
            chdir(__DIR__ . '/..');
            exec('tools/phpab --basedir src -t autoload-template.php --output src/autoload.php composer.json');
            chdir($dir);
            $map = file_get_contents(__DIR__ . '/autoload.php');
            $key = '\'' . strtolower($class) . '\' => ';
            preg_match('|' . preg_quote($key) . '(.*)|', $map, $matches);
            if (!isset($matches[1])) {
                return;
            }
            $filename = str_replace(['\'', ','], '', $matches[1]);
            require ___BASEDIR___$filename;
        }
    },
    ___EXCEPTION___,
    false
);
// @codeCoverageIgnoreEnd
